server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/LauraGullo/PatagoniaTest.git
          search-paths: config-data

  application:
    name: config-service
